---
- name: Redmine を起動する
  hosts: docker
  become: yes

  tasks:
    - name: (APT) 必要となるパッケージをインストールする
      apt:
        name: python-pip
        update_cache: yes

    - name: (PIP) 必要となるパッケージをインストールする
      pip:
        name: docker-py

    - name: PostgreSQL コンテナを起動する
      docker_container:
        name: postgresql
        image: "sameersbn/postgresql:9.4-22"
        env:
          DB_USER: redmine
          DB_PASS: password
          DB_NAME: redmine_production
        volumes:
          - "/srv/docker/redmine/postgresql:/var/lib/postgresql"

    - name: Redmine コンテナを起動する
      docker_container:
        name: redmine
        image: "sameersbn/redmine:3.3.0"
        links:
          - "postgresql:postgresql"
        env:
          TZ: "Asia/Tokyo"

          REDMINE_PORT: 10083
          REDMINE_HTTPS: false
          REDMINE_RELATIVE_URL_ROOT: ""
          REDMINE_SECRET_TOKEN: ""

          REDMINE_SUDO_MODE_ENABLED: false
          REDMINE_SUDO_MODE_TIMEOUT: 15

          REDMINE_CONCURRENT_UPLOADS: 2

          REDMINE_BACKUP_SCHEDULE: ""
          REDMINE_BACKUP_EXPIRY: ""
          REDMINE_BACKUP_TIME: ""

          SMTP_ENABLED: false
          SMTP_METHOD: smtp
          SMTP_DOMAIN: www.example.com
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_USER: mailer@example.com
          SMTP_PASS: password
          SMTP_STARTTLS: true
          SMTP_AUTHENTICATION: ":login"

          IMAP_ENABLED: false
          IMAP_HOST: imap.gmail.com
          IMAP_PORT: 993
          IMAP_USER: mailer@example.com
          IMAP_PASS: password
          IMAP_SSL: true
          IMAP_INTERVAL: 30

        ports:
          - "80:80"

        volumes:
          - "/srv/docker/redmine/redmine:/home/redmine/data"
