# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "shell", 
    path: "scripts/initial-setup.sh"

  # ========================================================= Management

  config.vm.define "mgmt" do |mgmt|
    mgmt.vm.hostname = "mgmt"
    mgmt.vm.network 'private_network', ip: "192.168.56.10"

    mgmt.vm.provision "shell", 
      path: "scripts/install-salt-master.sh"
  end

  # ========================================================= Switch
  
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.hostname = "haproxy"
    haproxy.vm.network 'private_network', ip: "192.168.56.11"
    haproxy.vm.network 'public_network'

    haproxy.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "haproxy"]
  end

    config.vm.define "haproxy2" do |haproxy2|
    haproxy2.vm.hostname = "haproxy2"
    haproxy2.vm.network 'private_network', ip: "192.168.56.17"
    haproxy2.vm.network 'public_network'

    haproxy2.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "haproxy"]
  end

  # ========================================================= Presentation

  config.vm.define "web1" do |web|
    web.vm.hostname = "web1"
    web.vm.network 'private_network', ip: "192.168.56.12"
    
    web.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "web"]
  end

  config.vm.define "web2" do |web|
    web.vm.hostname = "web2"
    web.vm.network 'private_network', ip: "192.168.56.13"

    web.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "web"]
  end

  # ========================================================= Logic

  config.vm.define "was1" do |was|
    was.vm.hostname = "was1"
    was.vm.network 'private_network', ip: "192.168.56.14"

    was.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "was"]
  end

  config.vm.define "was2" do |was|
    was.vm.hostname = "was2"
    was.vm.network 'private_network', ip: "192.168.56.15"

    was.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "was"]
  end

  # ========================================================= Data

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network 'private_network', ip: "192.168.56.16"

    db.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "db"]
  end

  config.vm.define "db2" do |db2|
    db2.vm.hostname = "db2"
    db2.vm.network 'private_network', ip: "192.168.56.18"

    db2.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "db"]
  end

  # ========================================================= monitoring
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.hostname = "monitoring"
    monitoring.vm.network 'private_network', ip: "192.168.56.19"

    monitoring.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "monitoring"]
  end

  # ========================================================= nfs
  config.vm.define "nfs" do |nfs|
    nfs.vm.hostname = "nfs"
    nfs.vm.network 'private_network', ip: "192.168.56.20"
  end
end