# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"

  # ========================================================= Management

  config.vm.define "bastion" do |bastion|
    bastion.vm.hostname = "bastion"
    bastion.vm.network 'private_network', ip: "192.168.56.10"

    bastion.vm.provision "shell", 
      path: "scripts/install-salt-master.sh"
  end

  # ========================================================= Switch
  
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.hostname = "haproxy"
    haproxy.vm.network 'private_network', ip: "192.168.56.11"

    haproxy.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "haproxy"]
  end

  # ========================================================= Presentation

  config.vm.define "web1" do |web|
    web.vm.hostname = "web1"
    web.vm.network 'private_network', ip: "192.168.56.12"
    
    web.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "web"]
  end

  config.vm.define "web2" do |web|
    web.vm.hostname = "web2"
    web.vm.network 'private_network', ip: "192.168.56.13"

    web.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "web"]
  end

  # ========================================================= Logic

  config.vm.define "was1" do |was|
    was.vm.hostname = "was1"
    was.vm.network 'private_network', ip: "192.168.56.14"

    was.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "was"]
  end

  config.vm.define "was2" do |was|
    was.vm.hostname = "was2"
    was.vm.network 'private_network', ip: "192.168.56.15"

    was.vm.provision "shell",
      path: "scripts/install-salt-minion.sh", 
      args: ["192.168.56.10", "was"]
  end

  # ========================================================= Data

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network 'private_network', ip: "192.168.56.16"
  end

end
