---
- name: Ubuntu 14.04 に Docker をインストールする
  hosts: docker
  become: yes

  tasks:
    - name: GPGキーを追加する
      apt_key:
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        id: "58118E89F3A912897C070ADBF76221572C52609D"

    - name: リポジトリを追加する
      apt_repository:
        repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"

    - name: パッケージをインストールする
      apt:
        update_cache: yes
        name: docker-engine
